/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/components/date.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/services/date.service';
import * as import9 from '../../../app/services/data.service';
import * as import10 from './css/date.component.css.shim';
import * as import11 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import12 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import13 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import14 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import15 from '@angular/core/src/linker/view_container';
import * as import16 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import20 from '@angular/forms/src/directives/default_value_accessor';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/ng_model';
import * as import23 from '@angular/forms/src/directives/ng_control';
import * as import24 from '@angular/forms/src/directives/ng_control_status';
import * as import25 from '@angular/common/src/directives/ng_for';
import * as import26 from '@angular/forms/src/directives/ng_form';
import * as import27 from '@angular/forms/src/directives/control_container';
export class Wrapper_DateComponent {
  /*private*/ _eventHandler:Function;
  context:import0.DateComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  subscription0:any;
  subscription1:any;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.DateComponent(p0,p1);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
  }
  check_currentDate(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.currentDate = currValue;
      this._expr_0 = currValue;
    }
  }
  check_hp(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.hp = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.updateCurrentDate.subscribe(_eventHandler.bind(view,'updateCurrentDate'))); }
    if (emit1) { (this.subscription1 = this.context.updateHp.subscribe(_eventHandler.bind(view,'updateHp'))); }
  }
}
var renderType_DateComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_DateComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.DateComponent>;
  _DateComponent_0_3:Wrapper_DateComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DateComponent_Host0,renderType_DateComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'date-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_DateComponent0(this.viewUtils,this,0,this._el_0);
    this._DateComponent_0_3 = new Wrapper_DateComponent(this.injectorGet(import8.DateService,this.parentIndex),this.injectorGet(import9.DataService,this.parentIndex));
    this.compView_0.create(this._DateComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._DateComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DateComponent) && (0 === requestNodeIndex))) { return this._DateComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DateComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._DateComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const DateComponentNgFactory:import7.ComponentFactory<import0.DateComponent> = new import7.ComponentFactory<import0.DateComponent>('date-component',View_DateComponent_Host0,import0.DateComponent);
const styles_DateComponent:any[] = [import10.styles];
var renderType_DateComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_DateComponent,{});
export class View_DateComponent0 extends import2.AppView<import0.DateComponent> {
  _el_0:any;
  _NgForm_0_3:import11.Wrapper_NgForm;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import12.Wrapper_NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _DefaultValueAccessor_11_3:import13.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_11_4:any[];
  _NgModel_11_5:import14.Wrapper_NgModel;
  _NgControl_11_6:any;
  _NgControlStatus_11_7:import12.Wrapper_NgControlStatus;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _vc_29:import15.ViewContainer;
  _TemplateRef_29_5:any;
  _NgFor_29_6:import16.Wrapper_NgFor;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _anchor_53:any;
  /*private*/ _vc_53:import15.ViewContainer;
  _TemplateRef_53_5:any;
  _NgFor_53_6:import16.Wrapper_NgFor;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  /*private*/ _expr_74:any;
  /*private*/ _expr_75:any;
  /*private*/ _expr_76:any;
  /*private*/ _expr_77:any;
  /*private*/ _expr_78:any;
  /*private*/ _expr_79:any;
  /*private*/ _expr_80:any;
  /*private*/ _expr_81:any;
  /*private*/ _expr_82:any;
  /*private*/ _expr_83:any;
  /*private*/ _expr_84:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DateComponent0,renderType_DateComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
    this._expr_74 = import1.UNINITIALIZED;
    this._expr_75 = import1.UNINITIALIZED;
    this._expr_76 = import1.UNINITIALIZED;
    this._expr_77 = import1.UNINITIALIZED;
    this._expr_78 = import1.UNINITIALIZED;
    this._expr_79 = import1.UNINITIALIZED;
    this._expr_80 = import1.UNINITIALIZED;
    this._expr_81 = import1.UNINITIALIZED;
    this._expr_82 = import1.UNINITIALIZED;
    this._expr_83 = import1.UNINITIALIZED;
    this._expr_84 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'form',new import3.InlineArray2(2,'novalidate',''),(null as any));
    this._NgForm_0_3 = new import11.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_0_4 = this._NgForm_0_3.context;
    this._NgControlStatusGroup_0_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Reference date:',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'span',new import3.InlineArray2(2,'class','span-inline'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'label',new import3.InlineArray2(2,'for','date-input'),(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_7,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_5,'input',new import3.InlineArray8(6,'id','date-input','name','ymd','type','text'),(null as any));
    this._DefaultValueAccessor_11_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_11));
    this._NG_VALUE_ACCESSOR_11_4 = [this._DefaultValueAccessor_11_3.context];
    this._NgModel_11_5 = new import14.Wrapper_NgModel(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_11_4);
    this._NgControl_11_6 = this._NgModel_11_5.context;
    this._NgControlStatus_11_7 = new import12.Wrapper_NgControlStatus(this._NgControl_11_6);
    this._text_12 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_0,'button',new import3.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Submit',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','div-inline'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'ul',new import3.InlineArray2(2,'class','nav nav-tabs'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'li',new import3.InlineArray2(2,'class','active dropdown'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'a',new import3.InlineArray8(6,'class','dropdown-toggle','data-toggle','dropdown','href',''),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'span',new import3.InlineArray2(2,'class','caret'),(null as any));
    this._text_26 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_21,'ul',new import3.InlineArray2(2,'class','dropdown-menu'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._vc_29 = new import15.ViewContainer(29,27,this,this._anchor_29);
    this._TemplateRef_29_5 = new import18.TemplateRef_(this,29,this._anchor_29);
    this._NgFor_29_6 = new import16.Wrapper_NgFor(this._vc_29.vcRef,this._TemplateRef_29_5,this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.ref);
    this._text_30 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._text_31 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_0,'button',new import3.InlineArray2(2,'class','btn btn-primary align-up'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'-',(null as any));
    this._text_37 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_0,'button',new import3.InlineArray2(2,'class','btn btn-primary align-up'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'+',(null as any));
    this._text_40 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','div-inline'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'\n        ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_41,'ul',new import3.InlineArray2(2,'class','nav nav-tabs'),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_43,'li',new import3.InlineArray2(2,'class','active dropdown'),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_45,'a',new import3.InlineArray8(6,'class','dropdown-toggle','data-toggle','dropdown','href',''),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_47,'span',new import3.InlineArray2(2,'class','caret'),(null as any));
    this._text_50 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_45,'ul',new import3.InlineArray2(2,'class','dropdown-menu'),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'\n                    ',(null as any));
    this._anchor_53 = this.renderer.createTemplateAnchor(this._el_51,(null as any));
    this._vc_53 = new import15.ViewContainer(53,51,this,this._anchor_53);
    this._TemplateRef_53_5 = new import18.TemplateRef_(this,53,this._anchor_53);
    this._NgFor_53_6 = new import16.Wrapper_NgFor(this._vc_53.vcRef,this._TemplateRef_53_5,this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.ref);
    this._text_54 = this.renderer.createText(this._el_51,'\n                ',(null as any));
    this._text_55 = this.renderer.createText(this._el_45,'\n            ',(null as any));
    this._text_56 = this.renderer.createText(this._el_43,'\n        ',(null as any));
    this._text_57 = this.renderer.createText(this._el_41,'\n    ',(null as any));
    this._text_58 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_59 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_0));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_11));
    this._NgModel_11_5.subscribe(this,this.eventHandler(this.handleEvent_11),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_14));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_35,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_35));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_38,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_38));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._anchor_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.DefaultValueAccessor) && (11 === requestNodeIndex))) { return this._DefaultValueAccessor_11_3.context; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (11 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_11_4; }
    if (((token === import22.NgModel) && (11 === requestNodeIndex))) { return this._NgModel_11_5.context; }
    if (((token === import23.NgControl) && (11 === requestNodeIndex))) { return this._NgControl_11_6; }
    if (((token === import24.NgControlStatus) && (11 === requestNodeIndex))) { return this._NgControlStatus_11_7.context; }
    if (((token === import18.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import25.NgFor) && (29 === requestNodeIndex))) { return this._NgFor_29_6.context; }
    if (((token === import18.TemplateRef) && (53 === requestNodeIndex))) { return this._TemplateRef_53_5; }
    if (((token === import25.NgFor) && (53 === requestNodeIndex))) { return this._NgFor_53_6.context; }
    if (((token === import26.NgForm) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._NgForm_0_3.context; }
    if (((token === import27.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._ControlContainer_0_4; }
    if (((token === import24.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._NgControlStatusGroup_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatusGroup_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this._DefaultValueAccessor_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_1_0:any = 'ymd';
    this._NgModel_11_5.check_name(currVal_11_1_0,throwOnChange,false);
    const currVal_11_1_1:any = this.context.inputDate.ymd;
    this._NgModel_11_5.check_model(currVal_11_1_1,throwOnChange,false);
    this._NgModel_11_5.ngDoCheck(this,this._el_11,throwOnChange);
    this._NgControlStatus_11_7.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_29_0_0:any = this.context.jumpOptions;
    this._NgFor_29_6.check_ngForOf(currVal_29_0_0,throwOnChange,false);
    this._NgFor_29_6.ngDoCheck(this,this._anchor_29,throwOnChange);
    const currVal_53_0_0:any = this.context.hpOptions;
    this._NgFor_53_6.check_ngForOf(currVal_53_0_0,throwOnChange,false);
    this._NgFor_53_6.ngDoCheck(this,this._anchor_53,throwOnChange);
    this._vc_29.detectChangesInNestedViews(throwOnChange);
    this._vc_53.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_0_5.checkHost(this,this,this._el_0,throwOnChange);
    const currVal_74:any = import3.inlineInterpolate(2,'Range: ',this.context.min,' to ',this.context.max,'');
    if (import3.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this.renderer.setText(this._text_9,currVal_74);
      this._expr_74 = currVal_74;
    }
    const currVal_75:any = this.context.currentDate;
    if (import3.checkBinding(throwOnChange,this._expr_75,currVal_75)) {
      this.renderer.setElementProperty(this._el_11,'placeholder',currVal_75);
      this._expr_75 = currVal_75;
    }
    const currVal_76:any = this.context.inputDate.valid;
    if (import3.checkBinding(throwOnChange,this._expr_76,currVal_76)) {
      this.renderer.setElementClass(this._el_11,'valid',currVal_76);
      this._expr_76 = currVal_76;
    }
    const currVal_77:boolean = !this.context.inputDate.valid;
    if (import3.checkBinding(throwOnChange,this._expr_77,currVal_77)) {
      this.renderer.setElementClass(this._el_11,'invalid',currVal_77);
      this._expr_77 = currVal_77;
    }
    this._NgControlStatus_11_7.checkHost(this,this,this._el_11,throwOnChange);
    const currVal_78:boolean = !this.context.inputDate.valid;
    if (import3.checkBinding(throwOnChange,this._expr_78,currVal_78)) {
      this.renderer.setElementProperty(this._el_14,'disabled',currVal_78);
      this._expr_78 = currVal_78;
    }
    const currVal_79:any = this.context.jumpTooltip;
    if (import3.checkBinding(throwOnChange,this._expr_79,currVal_79)) {
      this.renderer.setElementProperty(this._el_23,'title',currVal_79);
      this._expr_79 = currVal_79;
    }
    const currVal_80:any = import3.inlineInterpolate(2,'Jump trading ',this.context.jump,' ',((this.context.jump === 1)? 'day': 'days'),'');
    if (import3.checkBinding(throwOnChange,this._expr_80,currVal_80)) {
      this.renderer.setText(this._text_24,currVal_80);
      this._expr_80 = currVal_80;
    }
    const currVal_81:any = (this.context.currentDate === this.context.validDates[0]);
    if (import3.checkBinding(throwOnChange,this._expr_81,currVal_81)) {
      this.renderer.setElementProperty(this._el_35,'disabled',currVal_81);
      this._expr_81 = currVal_81;
    }
    const currVal_82:any = (this.context.currentDate === this.context.validDates[(this.context.validDates.length - 1)]);
    if (import3.checkBinding(throwOnChange,this._expr_82,currVal_82)) {
      this.renderer.setElementProperty(this._el_38,'disabled',currVal_82);
      this._expr_82 = currVal_82;
    }
    const currVal_83:any = this.context.hpTootlip;
    if (import3.checkBinding(throwOnChange,this._expr_83,currVal_83)) {
      this.renderer.setElementProperty(this._el_47,'title',currVal_83);
      this._expr_83 = currVal_83;
    }
    const currVal_84:any = import3.inlineInterpolate(2,'Holding Period: ',this.context.hp,'  trading ',((this.context.hp === 1)? 'day': 'days'),'');
    if (import3.checkBinding(throwOnChange,this._expr_84,currVal_84)) {
      this.renderer.setText(this._text_48,currVal_84);
      this._expr_84 = currVal_84;
    }
  }
  destroyInternal():void {
    this._vc_29.destroyNestedViews();
    this._vc_53.destroyNestedViews();
    this._NgModel_11_5.ngOnDestroy();
    this._NgForm_0_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 29)) { return new View_DateComponent1(this.viewUtils,this,29,this._anchor_29,this._vc_29); }
    if ((nodeIndex == 53)) { return new View_DateComponent2(this.viewUtils,this,53,this._anchor_53,this._vc_53); }
    return (null as any);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_11_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.inputDate.ymd = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'ngModelChange')) {
      const pd_sub_1:any = ((<any>this.context.flag($event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.submit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_35(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.increment('down')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_38(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.increment('up')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_DateComponent1 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_DateComponent1,renderType_DateComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_3 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = import3.inlineInterpolate(1,'',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_2,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.jump = this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_DateComponent2 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_DateComponent2,renderType_DateComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_3 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = import3.inlineInterpolate(1,'',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_2,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.updateHoldingPeriod(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}