/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/components/exploration.viewer';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/services/data.service';
import * as import9 from './css/exploration.viewer.css.shim';
import * as import10 from '@angular/core/src/linker/view_container';
import * as import11 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import12 from '../../../app/components/date.component';
import * as import13 from './date.component.ngfactory';
import * as import14 from '../../../app/components/stock.table';
import * as import15 from './stock.table.ngfactory';
import * as import16 from '../../../app/pipes/shorten.pipe';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import19 from '../../../app/services/date.service';
import * as import20 from '../../../app/services/quantile.service';
import * as import21 from '../../../app/services/coloring.service';
import * as import22 from '@angular/common/src/directives/ng_for';
export class Wrapper_ExplorationViewer {
  /*private*/ _eventHandler:Function;
  context:import0.ExplorationViewer;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.ExplorationViewer(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ExplorationViewer_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ExplorationViewer_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ExplorationViewer>;
  _ExplorationViewer_0_3:Wrapper_ExplorationViewer;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ExplorationViewer_Host0,renderType_ExplorationViewer_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'exploration-viewer',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ExplorationViewer0(this.viewUtils,this,0,this._el_0);
    this._ExplorationViewer_0_3 = new Wrapper_ExplorationViewer(this.injectorGet(import8.DataService,this.parentIndex));
    this.compView_0.create(this._ExplorationViewer_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ExplorationViewer_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ExplorationViewer) && (0 === requestNodeIndex))) { return this._ExplorationViewer_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ExplorationViewer_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ExplorationViewerNgFactory:import7.ComponentFactory<import0.ExplorationViewer> = new import7.ComponentFactory<import0.ExplorationViewer>('exploration-viewer',View_ExplorationViewer_Host0,import0.ExplorationViewer);
const styles_ExplorationViewer:any[] = [import9.styles];
var renderType_ExplorationViewer:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_ExplorationViewer,{});
export class View_ExplorationViewer0 extends import1.AppView<import0.ExplorationViewer> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _el_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _anchor_54:any;
  /*private*/ _vc_54:import10.ViewContainer;
  _TemplateRef_54_5:any;
  _NgFor_54_6:import11.Wrapper_NgFor;
  _text_55:any;
  _el_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _anchor_73:any;
  /*private*/ _vc_73:import10.ViewContainer;
  _TemplateRef_73_5:any;
  _NgFor_73_6:import11.Wrapper_NgFor;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _anchor_79:any;
  /*private*/ _vc_79:import10.ViewContainer;
  _TemplateRef_79_5:any;
  _NgFor_79_6:import11.Wrapper_NgFor;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _text_84:any;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _el_99:any;
  _text_100:any;
  _text_101:any;
  _text_102:any;
  _text_103:any;
  _text_104:any;
  _text_105:any;
  _text_106:any;
  _el_107:any;
  _text_108:any;
  _el_109:any;
  compView_109:import1.AppView<import12.DateComponent>;
  _DateComponent_109_3:import13.Wrapper_DateComponent;
  _text_110:any;
  _text_111:any;
  _text_112:any;
  _text_113:any;
  _el_114:any;
  compView_114:import1.AppView<import14.StockTable>;
  _StockTable_114_3:import15.Wrapper_StockTable;
  _text_115:any;
  /*private*/ _expr_129:any;
  /*private*/ _expr_130:any;
  _pipe_shorten_0:import16.ShortenPipe;
  /*private*/ _expr_132:any;
  /*private*/ _expr_133:any;
  /*private*/ _expr_134:any;
  /*private*/ _expr_135:any;
  /*private*/ _expr_136:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ExplorationViewer0,renderType_ExplorationViewer,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_129 = import6.UNINITIALIZED;
    this._expr_130 = import6.UNINITIALIZED;
    this._expr_132 = import6.UNINITIALIZED;
    this._expr_133 = import6.UNINITIALIZED;
    this._expr_134 = import6.UNINITIALIZED;
    this._expr_135 = import6.UNINITIALIZED;
    this._expr_136 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'nav',new import3.InlineArray2(2,'class','navbar navbar-default navbar-fixed-top'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_6 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'button',new import3.InlineArray16(10,'aria-expanded','false','class','navbar-toggle collapsed','data-target','#navbar-collapse-1','data-toggle','collapse','type','button'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Toggle navigation',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_9,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_15 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_9,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_17 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_9,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_19 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._text_20 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_7,'a',new import3.InlineArray8(6,'class','navbar-brand','href','https://www.goldminerpulse.com','target','_blank'),(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_21,'img',new import3.InlineArray4(4,'alt','Brand','src','https://www.goldminerpulse.com/favicon.ico'),(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'GoldMinerPulse',(null as any));
    this._text_25 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_26 = this.renderer.createText(this._el_4,'\n\n            ',(null as any));
    this._text_27 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray4(4,'class','collapse navbar-collapse','id','navbar-collapse-1'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n                ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'ul',new import3.InlineArray2(2,'class','nav navbar-nav'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n                    ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_32,'a',new import3.InlineArray4(4,'href','../about.php','target','_blank'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'About ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'(current)',(null as any));
    this._text_37 = this.renderer.createText(this._el_30,'\n                    ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_30,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_38,'a',new import3.InlineArray4(4,'href','../help.php','target','_blank'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Help',(null as any));
    this._text_41 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._text_42 = this.renderer.createText(this._el_28,'\n                ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_28,'ul',new import3.InlineArray2(2,'class','nav navbar-nav navbar-right'),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'\n                    ',(null as any));
    this._text_45 = this.renderer.createText(this._el_43,'\n                    ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_43,'li',new import3.InlineArray2(2,'class','dropdown'),(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'\n                        ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'a',new import3.InlineArray8(6,'class','dropdown-toggle','data-toggle','dropdown','href',''),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_48,'span',new import3.InlineArray2(2,'class','caret'),(null as any));
    this._text_51 = this.renderer.createText(this._el_46,'\n                        ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_46,'ul',new import3.InlineArray2(2,'class','dropdown-menu'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'\n                            ',(null as any));
    this._anchor_54 = this.renderer.createTemplateAnchor(this._el_52,(null as any));
    this._vc_54 = new import10.ViewContainer(54,52,this,this._anchor_54);
    this._TemplateRef_54_5 = new import17.TemplateRef_(this,54,this._anchor_54);
    this._NgFor_54_6 = new import11.Wrapper_NgFor(this._vc_54.vcRef,this._TemplateRef_54_5,this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.ref);
    this._text_55 = this.renderer.createText(this._el_52,'\n                            ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_52,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_56,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'',(null as any));
    this._text_59 = this.renderer.createText(this._el_56,'\n                            ',(null as any));
    this._text_60 = this.renderer.createText(this._el_52,'\n                        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_46,'\n                    ',(null as any));
    this._text_62 = this.renderer.createText(this._el_43,'\n                    ',(null as any));
    this._text_63 = this.renderer.createText(this._el_43,'\n                    ',(null as any));
    this._text_64 = this.renderer.createText(this._el_43,'\n                    ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_43,'li',new import3.InlineArray2(2,'class','dropdown'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'\n                        ',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_65,'a',new import3.InlineArray8(6,'class','dropdown-toggle','data-toggle','dropdown','href',''),(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'',(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_67,'span',new import3.InlineArray2(2,'class','caret'),(null as any));
    this._text_70 = this.renderer.createText(this._el_65,'\n                        ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_65,'ul',new import3.InlineArray2(2,'class','dropdown-menu'),(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'\n                            ',(null as any));
    this._anchor_73 = this.renderer.createTemplateAnchor(this._el_71,(null as any));
    this._vc_73 = new import10.ViewContainer(73,71,this,this._anchor_73);
    this._TemplateRef_73_5 = new import17.TemplateRef_(this,73,this._anchor_73);
    this._NgFor_73_6 = new import11.Wrapper_NgFor(this._vc_73.vcRef,this._TemplateRef_73_5,this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.ref);
    this._text_74 = this.renderer.createText(this._el_71,'\n                        ',(null as any));
    this._text_75 = this.renderer.createText(this._el_65,'\n                    ',(null as any));
    this._text_76 = this.renderer.createText(this._el_43,'\n                    ',(null as any));
    this._text_77 = this.renderer.createText(this._el_43,'\n                    ',(null as any));
    this._text_78 = this.renderer.createText(this._el_43,'\n                    ',(null as any));
    this._anchor_79 = this.renderer.createTemplateAnchor(this._el_43,(null as any));
    this._vc_79 = new import10.ViewContainer(79,43,this,this._anchor_79);
    this._TemplateRef_79_5 = new import17.TemplateRef_(this,79,this._anchor_79);
    this._NgFor_79_6 = new import11.Wrapper_NgFor(this._vc_79.vcRef,this._TemplateRef_79_5,this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.ref);
    this._text_80 = this.renderer.createText(this._el_43,'\n                    ',(null as any));
    this._text_81 = this.renderer.createText(this._el_43,'\n                ',(null as any));
    this._text_82 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._text_83 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_84 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_85 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_86 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_87 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_88 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'id','masthead'),(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'\n    ',(null as any));
    this._el_91 = import3.createRenderElement(this.renderer,this._el_89,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_92 = this.renderer.createText(this._el_91,'\n        ',(null as any));
    this._el_93 = import3.createRenderElement(this.renderer,this._el_91,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_94 = this.renderer.createText(this._el_93,'\n            ',(null as any));
    this._el_95 = import3.createRenderElement(this.renderer,this._el_93,'div',new import3.InlineArray2(2,'class','col-md-7'),(null as any));
    this._text_96 = this.renderer.createText(this._el_95,'\n                ',(null as any));
    this._el_97 = import3.createRenderElement(this.renderer,this._el_95,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'',(null as any));
    this._el_99 = import3.createRenderElement(this.renderer,this._el_97,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_100 = this.renderer.createText(this._el_99,'',(null as any));
    this._text_101 = this.renderer.createText(this._el_97,'\n                ',(null as any));
    this._text_102 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._text_103 = this.renderer.createText(this._el_93,'\n        ',(null as any));
    this._text_104 = this.renderer.createText(this._el_91,'\n    ',(null as any));
    this._text_105 = this.renderer.createText(this._el_89,'\n',(null as any));
    this._text_106 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_107 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','well'),(null as any));
    this._text_108 = this.renderer.createText(this._el_107,'\n    ',(null as any));
    this._el_109 = import3.createRenderElement(this.renderer,this._el_107,'date-component',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_109 = new import13.View_DateComponent0(this.viewUtils,this,109,this._el_109);
    this._DateComponent_109_3 = new import13.Wrapper_DateComponent(this.parentView.injectorGet(import19.DateService,this.parentIndex),this.parentView.injectorGet(import8.DataService,this.parentIndex));
    this._text_110 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_109.create(this._DateComponent_109_3.context);
    this._text_111 = this.renderer.createText(this._el_107,'\n',(null as any));
    this._text_112 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_113 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_114 = import3.createRenderElement(this.renderer,parentRenderNode,'stock-table',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_114 = new import15.View_StockTable0(this.viewUtils,this,114,this._el_114);
    this._StockTable_114_3 = new import15.Wrapper_StockTable(this.parentView.injectorGet(import20.QuantileService,this.parentIndex),this.parentView.injectorGet(import21.ColoringService,this.parentIndex));
    this.compView_114.create(this._StockTable_114_3.context);
    this._text_115 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._pipe_shorten_0 = new import16.ShortenPipe();
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_57,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_57));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_109,new import3.InlineArray4(4,'updateHp',(null as any),'updateCurrentDate',(null as any)),this.eventHandler(this.handleEvent_109));
    this._DateComponent_109_3.subscribe(this,this.eventHandler(this.handleEvent_109),true,true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._el_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._anchor_54,
      this._text_55,
      this._el_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._anchor_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._anchor_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._text_85,
      this._text_86,
      this._text_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._text_101,
      this._text_102,
      this._text_103,
      this._text_104,
      this._text_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._text_111,
      this._text_112,
      this._text_113,
      this._el_114,
      this._text_115
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (54 === requestNodeIndex))) { return this._TemplateRef_54_5; }
    if (((token === import22.NgFor) && (54 === requestNodeIndex))) { return this._NgFor_54_6.context; }
    if (((token === import17.TemplateRef) && (73 === requestNodeIndex))) { return this._TemplateRef_73_5; }
    if (((token === import22.NgFor) && (73 === requestNodeIndex))) { return this._NgFor_73_6.context; }
    if (((token === import17.TemplateRef) && (79 === requestNodeIndex))) { return this._TemplateRef_79_5; }
    if (((token === import22.NgFor) && (79 === requestNodeIndex))) { return this._NgFor_79_6.context; }
    if (((token === import12.DateComponent) && ((109 <= requestNodeIndex) && (requestNodeIndex <= 110)))) { return this._DateComponent_109_3.context; }
    if (((token === import14.StockTable) && (114 === requestNodeIndex))) { return this._StockTable_114_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import6.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_54_0_0:any = valUnwrapper.unwrap(this._pipe_shorten_0.transform(this.context.limitOptions,this.context.stocks.length));
    this._NgFor_54_6.check_ngForOf(currVal_54_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgFor_54_6.ngDoCheck(this,this._anchor_54,throwOnChange);
    const currVal_73_0_0:any = this.context.spreadOptions;
    this._NgFor_73_6.check_ngForOf(currVal_73_0_0,throwOnChange,false);
    this._NgFor_73_6.ngDoCheck(this,this._anchor_73,throwOnChange);
    const currVal_79_0_0:any = this.context.thresholds;
    this._NgFor_79_6.check_ngForOf(currVal_79_0_0,throwOnChange,false);
    this._NgFor_79_6.ngDoCheck(this,this._anchor_79,throwOnChange);
    const currVal_109_0_0:any = this.context.currentDate;
    this._DateComponent_109_3.check_currentDate(currVal_109_0_0,throwOnChange,false);
    const currVal_109_0_1:any = this.context.hp;
    this._DateComponent_109_3.check_hp(currVal_109_0_1,throwOnChange,false);
    this._DateComponent_109_3.ngDoCheck(this,this._el_109,throwOnChange);
    const currVal_114_0_0:any = this.context.stocks;
    this._StockTable_114_3.check_stocks(currVal_114_0_0,throwOnChange,false);
    const currVal_114_0_1:any = this.context.metaDefs;
    this._StockTable_114_3.check_metaDefs(currVal_114_0_1,throwOnChange,false);
    const currVal_114_0_2:any = this.context.currentDate;
    this._StockTable_114_3.check_currentDate(currVal_114_0_2,throwOnChange,false);
    const currVal_114_0_3:any = this.context.futureDates;
    this._StockTable_114_3.check_futureDates(currVal_114_0_3,throwOnChange,false);
    const currVal_114_0_4:any = this.context.cpMetaDefs;
    this._StockTable_114_3.check_cpMetaDefs(currVal_114_0_4,throwOnChange,false);
    const currVal_114_0_5:any = this.context.benchmarks;
    this._StockTable_114_3.check_benchmarks(currVal_114_0_5,throwOnChange,false);
    const currVal_114_0_6:any = this.context.limit;
    this._StockTable_114_3.check_limit(currVal_114_0_6,throwOnChange,false);
    const currVal_114_0_7:any = this.context.spread;
    this._StockTable_114_3.check_spread(currVal_114_0_7,throwOnChange,false);
    const currVal_114_0_8:any = this.context.activeThresholds;
    this._StockTable_114_3.check_thresholds(currVal_114_0_8,throwOnChange,false);
    this._StockTable_114_3.ngDoCheck(this,this._el_114,throwOnChange);
    this._vc_54.detectChangesInNestedViews(throwOnChange);
    this._vc_73.detectChangesInNestedViews(throwOnChange);
    this._vc_79.detectChangesInNestedViews(throwOnChange);
    const currVal_129:any = this.context.limitTooltip;
    if (import3.checkBinding(throwOnChange,this._expr_129,currVal_129)) {
      this.renderer.setElementProperty(this._el_48,'title',currVal_129);
      this._expr_129 = currVal_129;
    }
    const currVal_130:any = import3.inlineInterpolate(2,'',this.context.limitText,': ',this.context.limit,' ');
    if (import3.checkBinding(throwOnChange,this._expr_130,currVal_130)) {
      this.renderer.setText(this._text_49,currVal_130);
      this._expr_130 = currVal_130;
    }
    const currVal_132:any = import3.inlineInterpolate(1,'',this.context.stocks.length,'');
    if (import3.checkBinding(throwOnChange,this._expr_132,currVal_132)) {
      this.renderer.setText(this._text_58,currVal_132);
      this._expr_132 = currVal_132;
    }
    const currVal_133:any = this.context.spreadTootlip;
    if (import3.checkBinding(throwOnChange,this._expr_133,currVal_133)) {
      this.renderer.setElementProperty(this._el_67,'title',currVal_133);
      this._expr_133 = currVal_133;
    }
    const currVal_134:any = import3.inlineInterpolate(2,'',this.context.spreadText,': ',this.context.spread,' ');
    if (import3.checkBinding(throwOnChange,this._expr_134,currVal_134)) {
      this.renderer.setText(this._text_68,currVal_134);
      this._expr_134 = currVal_134;
    }
    const currVal_135:any = import3.inlineInterpolate(1,' ',this.context.title,'\n                    ');
    if (import3.checkBinding(throwOnChange,this._expr_135,currVal_135)) {
      this.renderer.setText(this._text_98,currVal_135);
      this._expr_135 = currVal_135;
    }
    const currVal_136:any = import3.inlineInterpolate(1,'',this.context.subtitle,'');
    if (import3.checkBinding(throwOnChange,this._expr_136,currVal_136)) {
      this.renderer.setText(this._text_100,currVal_136);
      this._expr_136 = currVal_136;
    }
    this.compView_109.detectChanges(throwOnChange);
    this.compView_114.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_54.destroyNestedViews();
    this._vc_73.destroyNestedViews();
    this._vc_79.destroyNestedViews();
    this.compView_109.destroy();
    this.compView_114.destroy();
    this._DateComponent_109_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 54)) { return new View_ExplorationViewer1(this.viewUtils,this,54,this._anchor_54,this._vc_54); }
    if ((nodeIndex == 73)) { return new View_ExplorationViewer2(this.viewUtils,this,73,this._anchor_73,this._vc_73); }
    if ((nodeIndex == 79)) { return new View_ExplorationViewer3(this.viewUtils,this,79,this._anchor_79,this._vc_79); }
    return (null as any);
  }
  handleEvent_57(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.limit = this.context.stocks.length)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_109(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'updateHp')) {
      const pd_sub_0:any = ((<any>this.context.update($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'updateCurrentDate')) {
      const pd_sub_1:any = ((<any>this.context.update($event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}
class View_ExplorationViewer1 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ExplorationViewer1,renderType_ExplorationViewer,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_3 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = import3.inlineInterpolate(1,'',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_2,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.limit = this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ExplorationViewer2 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ExplorationViewer2,renderType_ExplorationViewer,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_3 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = import3.inlineInterpolate(1,'',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_2,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.modifySpread(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ExplorationViewer3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _vc_12:import10.ViewContainer;
  _TemplateRef_12_5:any;
  _NgFor_12_6:import11.Wrapper_NgFor;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _vc_14:import10.ViewContainer;
  _TemplateRef_14_5:any;
  _NgFor_14_6:import11.Wrapper_NgFor;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _vc_16:import10.ViewContainer;
  _TemplateRef_16_5:any;
  _NgFor_16_6:import11.Wrapper_NgFor;
  _text_17:any;
  _text_18:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ExplorationViewer3,renderType_ExplorationViewer,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_28 = import6.UNINITIALIZED;
    this._expr_29 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray2(2,'class',' dropdown'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray8(6,'class','dropdown-toggle','data-toggle','dropdown','href',''),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'span',new import3.InlineArray2(2,'class','caret'),(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_0,'ul',new import3.InlineArray2(2,'class','dropdown-menu'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_8,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'none',(null as any));
    this._text_11 = this.renderer.createText(this._el_6,'\n                            ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_12 = new import10.ViewContainer(12,6,this,this._anchor_12);
    this._TemplateRef_12_5 = new import17.TemplateRef_(this,12,this._anchor_12);
    this._NgFor_12_6 = new import11.Wrapper_NgFor(this._vc_12.vcRef,this._TemplateRef_12_5,this.parentView.parentView.injectorGet(import18.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_13 = this.renderer.createText(this._el_6,'\n                            ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_14 = new import10.ViewContainer(14,6,this,this._anchor_14);
    this._TemplateRef_14_5 = new import17.TemplateRef_(this,14,this._anchor_14);
    this._NgFor_14_6 = new import11.Wrapper_NgFor(this._vc_14.vcRef,this._TemplateRef_14_5,this.parentView.parentView.injectorGet(import18.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_15 = this.renderer.createText(this._el_6,'\n                            ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_16 = new import10.ViewContainer(16,6,this,this._anchor_16);
    this._TemplateRef_16_5 = new import17.TemplateRef_(this,16,this._anchor_16);
    this._NgFor_16_6 = new import11.Wrapper_NgFor(this._vc_16.vcRef,this._TemplateRef_16_5,this.parentView.parentView.injectorGet(import18.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_17 = this.renderer.createText(this._el_6,'\n                        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_9));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import22.NgFor) && (12 === requestNodeIndex))) { return this._NgFor_12_6.context; }
    if (((token === import17.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import22.NgFor) && (14 === requestNodeIndex))) { return this._NgFor_14_6.context; }
    if (((token === import17.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import22.NgFor) && (16 === requestNodeIndex))) { return this._NgFor_16_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_12_0_0:any = this.context.$implicit.gt;
    this._NgFor_12_6.check_ngForOf(currVal_12_0_0,throwOnChange,false);
    this._NgFor_12_6.ngDoCheck(this,this._anchor_12,throwOnChange);
    const currVal_14_0_0:any = this.context.$implicit.lt;
    this._NgFor_14_6.check_ngForOf(currVal_14_0_0,throwOnChange,false);
    this._NgFor_14_6.ngDoCheck(this,this._anchor_14,throwOnChange);
    const currVal_16_0_0:any = this.context.$implicit.eq;
    this._NgFor_16_6.check_ngForOf(currVal_16_0_0,throwOnChange,false);
    this._NgFor_16_6.ngDoCheck(this,this._anchor_16,throwOnChange);
    this._vc_12.detectChangesInNestedViews(throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    this._vc_16.detectChangesInNestedViews(throwOnChange);
    const currVal_28:any = (this.context.$implicit.text? this.context.$implicit.text: this.context.$implicit.sid);
    if (import3.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementProperty(this._el_2,'title',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = import3.inlineInterpolate(2,'',this.context.$implicit.short,' ',this.parentView.context.displayThreshold(this.context.$implicit.sid),' ');
    if (import3.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setText(this._text_3,currVal_29);
      this._expr_29 = currVal_29;
    }
  }
  destroyInternal():void {
    this._vc_12.destroyNestedViews();
    this._vc_14.destroyNestedViews();
    this._vc_16.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 12)) { return new View_ExplorationViewer4(this.viewUtils,this,12,this._anchor_12,this._vc_12); }
    if ((nodeIndex == 14)) { return new View_ExplorationViewer5(this.viewUtils,this,14,this._anchor_14,this._vc_14); }
    if ((nodeIndex == 16)) { return new View_ExplorationViewer6(this.viewUtils,this,16,this._anchor_16,this._vc_16); }
    return (null as any);
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.deactivateThreshold(this.context.$implicit.sid)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ExplorationViewer4 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ExplorationViewer4,renderType_ExplorationViewer,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_3 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = import3.inlineInterpolate(1,' at least ',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_2,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.activateThreshold(this.parentView.context.$implicit.sid,'gt',this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ExplorationViewer5 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ExplorationViewer5,renderType_ExplorationViewer,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_3 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = import3.inlineInterpolate(1,' at most ',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_2,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.activateThreshold(this.parentView.context.$implicit.sid,'lt',this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ExplorationViewer6 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_ExplorationViewer6,renderType_ExplorationViewer,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_3 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = import3.inlineInterpolate(1,'',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_2,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.activateThreshold(this.parentView.context.$implicit.sid,'eq',this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}