/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/components/stock.table';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/services/quantile.service';
import * as import9 from '../../../app/services/coloring.service';
import * as import10 from './css/stock.table.css.shim';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import13 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import14 from '../../../app/pipes/metric.pipe';
import * as import15 from '../../../app/pipes/custom-percent.pipe';
import * as import16 from '../../../app/pipes/format.pipe';
import * as import17 from '../../../app/pipes/match.pipe';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import20 from '@angular/common/src/directives/ng_for';
import * as import21 from '@angular/common/src/directives/ng_if';
import * as import22 from '../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import23 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from '@angular/common/src/directives/ng_class';
import * as import26 from '../../../app/pipes/threshold.pipe';
import * as import27 from '../../../app/pipes/sort.pipe';
import * as import28 from '@angular/common/src/pipes/slice_pipe';
export class Wrapper_StockTable {
  /*private*/ _eventHandler:Function;
  context:import0.StockTable;
  /*private*/ _changed:boolean;
  /*private*/ _changes:{[key: string]:any};
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this._changes = {};
    this.context = new import0.StockTable(p0,p1);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
    this._expr_5 = import1.UNINITIALIZED;
    this._expr_6 = import1.UNINITIALIZED;
    this._expr_7 = import1.UNINITIALIZED;
    this._expr_8 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_stocks(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.stocks = currValue;
      this._changes['stocks'] = new import1.SimpleChange(this._expr_0,currValue);
      this._expr_0 = currValue;
    }
  }
  check_metaDefs(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.metaDefs = currValue;
      this._changes['metaDefs'] = new import1.SimpleChange(this._expr_1,currValue);
      this._expr_1 = currValue;
    }
  }
  check_currentDate(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.currentDate = currValue;
      this._changes['currentDate'] = new import1.SimpleChange(this._expr_2,currValue);
      this._expr_2 = currValue;
    }
  }
  check_futureDates(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_3,currValue))) {
      this._changed = true;
      this.context.futureDates = currValue;
      this._changes['futureDates'] = new import1.SimpleChange(this._expr_3,currValue);
      this._expr_3 = currValue;
    }
  }
  check_cpMetaDefs(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_4,currValue))) {
      this._changed = true;
      this.context.cpMetaDefs = currValue;
      this._changes['cpMetaDefs'] = new import1.SimpleChange(this._expr_4,currValue);
      this._expr_4 = currValue;
    }
  }
  check_benchmarks(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_5,currValue))) {
      this._changed = true;
      this.context.benchmarks = currValue;
      this._changes['benchmarks'] = new import1.SimpleChange(this._expr_5,currValue);
      this._expr_5 = currValue;
    }
  }
  check_limit(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_6,currValue))) {
      this._changed = true;
      this.context.limit = currValue;
      this._changes['limit'] = new import1.SimpleChange(this._expr_6,currValue);
      this._expr_6 = currValue;
    }
  }
  check_spread(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_7,currValue))) {
      this._changed = true;
      this.context.spread = currValue;
      this._changes['spread'] = new import1.SimpleChange(this._expr_7,currValue);
      this._expr_7 = currValue;
    }
  }
  check_thresholds(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_8,currValue))) {
      this._changed = true;
      this.context.thresholds = currValue;
      this._changes['thresholds'] = new import1.SimpleChange(this._expr_8,currValue);
      this._expr_8 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if (changed) {
      this.context.ngOnChanges(this._changes);
      this._changes = {};
    } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_StockTable_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_StockTable_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.StockTable>;
  _StockTable_0_3:Wrapper_StockTable;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_StockTable_Host0,renderType_StockTable_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'stock-table',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_StockTable0(this.viewUtils,this,0,this._el_0);
    this._StockTable_0_3 = new Wrapper_StockTable(this.injectorGet(import8.QuantileService,this.parentIndex),this.injectorGet(import9.ColoringService,this.parentIndex));
    this.compView_0.create(this._StockTable_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._StockTable_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.StockTable) && (0 === requestNodeIndex))) { return this._StockTable_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._StockTable_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const StockTableNgFactory:import7.ComponentFactory<import0.StockTable> = new import7.ComponentFactory<import0.StockTable>('stock-table',View_StockTable_Host0,import0.StockTable);
const styles_StockTable:any[] = [import10.styles];
var renderType_StockTable:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_StockTable,{});
export class View_StockTable0 extends import2.AppView<import0.StockTable> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _anchor_44:any;
  /*private*/ _vc_44:import11.ViewContainer;
  _TemplateRef_44_5:any;
  _NgFor_44_6:import12.Wrapper_NgFor;
  _text_45:any;
  _anchor_46:any;
  /*private*/ _vc_46:import11.ViewContainer;
  _TemplateRef_46_5:any;
  _NgFor_46_6:import12.Wrapper_NgFor;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _text_62:any;
  _anchor_63:any;
  /*private*/ _vc_63:import11.ViewContainer;
  _TemplateRef_63_5:any;
  _NgFor_63_6:import12.Wrapper_NgFor;
  _text_64:any;
  _anchor_65:any;
  /*private*/ _vc_65:import11.ViewContainer;
  _TemplateRef_65_5:any;
  _NgFor_65_6:import12.Wrapper_NgFor;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _anchor_82:any;
  /*private*/ _vc_82:import11.ViewContainer;
  _TemplateRef_82_5:any;
  _NgFor_82_6:import12.Wrapper_NgFor;
  _text_83:any;
  _anchor_84:any;
  /*private*/ _vc_84:import11.ViewContainer;
  _TemplateRef_84_5:any;
  _NgFor_84_6:import12.Wrapper_NgFor;
  _text_85:any;
  _anchor_86:any;
  /*private*/ _vc_86:import11.ViewContainer;
  _TemplateRef_86_5:any;
  _NgIf_86_6:import13.Wrapper_NgIf;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _anchor_90:any;
  /*private*/ _vc_90:import11.ViewContainer;
  _TemplateRef_90_5:any;
  _NgIf_90_6:import13.Wrapper_NgIf;
  _text_91:any;
  _text_92:any;
  _text_93:any;
  /*private*/ _expr_118:any;
  _pipe_metric_0:import14.MetricPipe;
  _pipe_metric_0_0:any;
  /*private*/ _expr_121:any;
  /*private*/ _expr_122:any;
  /*private*/ _expr_123:any;
  _pipe_metric_0_1:any;
  _pipe_cpercent_1:import15.CustomPercentPipe;
  _pipe_format_2:import16.FormatPipe;
  _pipe_match_3:import17.MatchPipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_StockTable0,renderType_StockTable,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
    this._expr_118 = import1.UNINITIALIZED;
    this._expr_121 = import1.UNINITIALIZED;
    this._expr_122 = import1.UNINITIALIZED;
    this._expr_123 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','well table-responsive'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'table',new import3.InlineArray2(2,'class','table table-striped table-condensed'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'caption',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_4,'ul',new import3.InlineArray2(2,'class','legend'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_13,'span',new import3.InlineArray2(2,'class','q1'),(null as any));
    this._text_15 = this.renderer.createText(this._el_13,' Quartile 1',(null as any));
    this._text_16 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_11,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_17,'span',new import3.InlineArray2(2,'class','q2'),(null as any));
    this._text_19 = this.renderer.createText(this._el_17,' Quartile 2',(null as any));
    this._text_20 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_11,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_21,'span',new import3.InlineArray2(2,'class','q3'),(null as any));
    this._text_23 = this.renderer.createText(this._el_21,' Quartile 3',(null as any));
    this._text_24 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_11,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_25,'span',new import3.InlineArray2(2,'class','q4'),(null as any));
    this._text_27 = this.renderer.createText(this._el_25,' Quartile 4',(null as any));
    this._text_28 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._text_29 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_30 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_2,'thead',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,' Reference Date',(null as any));
    this._text_37 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_33,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_39 = this.renderer.createText(this._el_38,' Limit',(null as any));
    this._text_40 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_33,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_42 = this.renderer.createText(this._el_41,' Spread',(null as any));
    this._text_43 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._anchor_44 = this.renderer.createTemplateAnchor(this._el_33,(null as any));
    this._vc_44 = new import11.ViewContainer(44,33,this,this._anchor_44);
    this._TemplateRef_44_5 = new import18.TemplateRef_(this,44,this._anchor_44);
    this._NgFor_44_6 = new import12.Wrapper_NgFor(this._vc_44.vcRef,this._TemplateRef_44_5,this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.ref);
    this._text_45 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._anchor_46 = this.renderer.createTemplateAnchor(this._el_33,(null as any));
    this._vc_46 = new import11.ViewContainer(46,33,this,this._anchor_46);
    this._TemplateRef_46_5 = new import18.TemplateRef_(this,46,this._anchor_46);
    this._NgFor_46_6 = new import12.Wrapper_NgFor(this._vc_46.vcRef,this._TemplateRef_46_5,this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.ref);
    this._text_47 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._text_48 = this.renderer.createText(this._el_31,'\n        ',(null as any));
    this._text_49 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_2,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n            ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_50,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'\n                ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_52,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'',(null as any));
    this._text_56 = this.renderer.createText(this._el_52,'\n                ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_52,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'',(null as any));
    this._text_59 = this.renderer.createText(this._el_52,'\n                ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_52,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'',(null as any));
    this._text_62 = this.renderer.createText(this._el_52,'\n                ',(null as any));
    this._anchor_63 = this.renderer.createTemplateAnchor(this._el_52,(null as any));
    this._vc_63 = new import11.ViewContainer(63,52,this,this._anchor_63);
    this._TemplateRef_63_5 = new import18.TemplateRef_(this,63,this._anchor_63);
    this._NgFor_63_6 = new import12.Wrapper_NgFor(this._vc_63.vcRef,this._TemplateRef_63_5,this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.ref);
    this._text_64 = this.renderer.createText(this._el_52,'\n                ',(null as any));
    this._anchor_65 = this.renderer.createTemplateAnchor(this._el_52,(null as any));
    this._vc_65 = new import11.ViewContainer(65,52,this,this._anchor_65);
    this._TemplateRef_65_5 = new import18.TemplateRef_(this,65,this._anchor_65);
    this._NgFor_65_6 = new import12.Wrapper_NgFor(this._vc_65.vcRef,this._TemplateRef_65_5,this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.ref);
    this._text_66 = this.renderer.createText(this._el_52,'\n            ',(null as any));
    this._text_67 = this.renderer.createText(this._el_50,'\n        ',(null as any));
    this._text_68 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_69 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_70 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','well table-responsive'),(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'\n    ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_71,'table',new import3.InlineArray2(2,'class','table table-striped table-hover table-bordered table-condensed'),(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'\n        ',(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_73,'thead',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_76 = this.renderer.createText(this._el_75,'\n            ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_75,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'\n                ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_77,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'#',(null as any));
    this._text_81 = this.renderer.createText(this._el_77,'\n                ',(null as any));
    this._anchor_82 = this.renderer.createTemplateAnchor(this._el_77,(null as any));
    this._vc_82 = new import11.ViewContainer(82,77,this,this._anchor_82);
    this._TemplateRef_82_5 = new import18.TemplateRef_(this,82,this._anchor_82);
    this._NgFor_82_6 = new import12.Wrapper_NgFor(this._vc_82.vcRef,this._TemplateRef_82_5,this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.ref);
    this._text_83 = this.renderer.createText(this._el_77,'\n                ',(null as any));
    this._anchor_84 = this.renderer.createTemplateAnchor(this._el_77,(null as any));
    this._vc_84 = new import11.ViewContainer(84,77,this,this._anchor_84);
    this._TemplateRef_84_5 = new import18.TemplateRef_(this,84,this._anchor_84);
    this._NgFor_84_6 = new import12.Wrapper_NgFor(this._vc_84.vcRef,this._TemplateRef_84_5,this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.ref);
    this._text_85 = this.renderer.createText(this._el_77,'\n                ',(null as any));
    this._anchor_86 = this.renderer.createTemplateAnchor(this._el_77,(null as any));
    this._vc_86 = new import11.ViewContainer(86,77,this,this._anchor_86);
    this._TemplateRef_86_5 = new import18.TemplateRef_(this,86,this._anchor_86);
    this._NgIf_86_6 = new import13.Wrapper_NgIf(this._vc_86.vcRef,this._TemplateRef_86_5);
    this._text_87 = this.renderer.createText(this._el_77,'\n            ',(null as any));
    this._text_88 = this.renderer.createText(this._el_75,'\n        ',(null as any));
    this._text_89 = this.renderer.createText(this._el_73,'\n        ',(null as any));
    this._anchor_90 = this.renderer.createTemplateAnchor(this._el_73,(null as any));
    this._vc_90 = new import11.ViewContainer(90,73,this,this._anchor_90);
    this._TemplateRef_90_5 = new import18.TemplateRef_(this,90,this._anchor_90);
    this._NgIf_90_6 = new import13.Wrapper_NgIf(this._vc_90.vcRef,this._TemplateRef_90_5);
    this._text_91 = this.renderer.createText(this._el_73,'\n    ',(null as any));
    this._text_92 = this.renderer.createText(this._el_71,'\n\n',(null as any));
    this._text_93 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._pipe_metric_0 = new import14.MetricPipe();
    this._pipe_metric_0_0 = import3.pureProxy1(this._pipe_metric_0.transform.bind(this._pipe_metric_0));
    this._pipe_metric_0_1 = import3.pureProxy1(this._pipe_metric_0.transform.bind(this._pipe_metric_0));
    this._pipe_cpercent_1 = new import15.CustomPercentPipe();
    this._pipe_format_2 = new import16.FormatPipe();
    this._pipe_match_3 = new import17.MatchPipe();
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._anchor_44,
      this._text_45,
      this._anchor_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._anchor_63,
      this._text_64,
      this._anchor_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._anchor_82,
      this._text_83,
      this._anchor_84,
      this._text_85,
      this._anchor_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._anchor_90,
      this._text_91,
      this._text_92,
      this._text_93
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (44 === requestNodeIndex))) { return this._TemplateRef_44_5; }
    if (((token === import20.NgFor) && (44 === requestNodeIndex))) { return this._NgFor_44_6.context; }
    if (((token === import18.TemplateRef) && (46 === requestNodeIndex))) { return this._TemplateRef_46_5; }
    if (((token === import20.NgFor) && (46 === requestNodeIndex))) { return this._NgFor_46_6.context; }
    if (((token === import18.TemplateRef) && (63 === requestNodeIndex))) { return this._TemplateRef_63_5; }
    if (((token === import20.NgFor) && (63 === requestNodeIndex))) { return this._NgFor_63_6.context; }
    if (((token === import18.TemplateRef) && (65 === requestNodeIndex))) { return this._TemplateRef_65_5; }
    if (((token === import20.NgFor) && (65 === requestNodeIndex))) { return this._NgFor_65_6.context; }
    if (((token === import18.TemplateRef) && (82 === requestNodeIndex))) { return this._TemplateRef_82_5; }
    if (((token === import20.NgFor) && (82 === requestNodeIndex))) { return this._NgFor_82_6.context; }
    if (((token === import18.TemplateRef) && (84 === requestNodeIndex))) { return this._TemplateRef_84_5; }
    if (((token === import20.NgFor) && (84 === requestNodeIndex))) { return this._NgFor_84_6.context; }
    if (((token === import18.TemplateRef) && (86 === requestNodeIndex))) { return this._TemplateRef_86_5; }
    if (((token === import21.NgIf) && (86 === requestNodeIndex))) { return this._NgIf_86_6.context; }
    if (((token === import18.TemplateRef) && (90 === requestNodeIndex))) { return this._TemplateRef_90_5; }
    if (((token === import21.NgIf) && (90 === requestNodeIndex))) { return this._NgIf_90_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_44_0_0:any = valUnwrapper.unwrap(import3.castByValue(this._pipe_metric_0_0,this._pipe_metric_0.transform)(this.context.metaDefs));
    this._NgFor_44_6.check_ngForOf(currVal_44_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgFor_44_6.ngDoCheck(this,this._anchor_44,throwOnChange);
    const currVal_46_0_0:any = this.context.cpMetaDefs;
    this._NgFor_46_6.check_ngForOf(currVal_46_0_0,throwOnChange,false);
    this._NgFor_46_6.ngDoCheck(this,this._anchor_46,throwOnChange);
    valUnwrapper.reset();
    const currVal_63_0_0:any = valUnwrapper.unwrap(import3.castByValue(this._pipe_metric_0_1,this._pipe_metric_0.transform)(this.context.metaDefs));
    this._NgFor_63_6.check_ngForOf(currVal_63_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgFor_63_6.ngDoCheck(this,this._anchor_63,throwOnChange);
    const currVal_65_0_0:any = this.context.cpMetaDefs;
    this._NgFor_65_6.check_ngForOf(currVal_65_0_0,throwOnChange,false);
    this._NgFor_65_6.ngDoCheck(this,this._anchor_65,throwOnChange);
    const currVal_82_0_0:any = this.context.metaDefs;
    this._NgFor_82_6.check_ngForOf(currVal_82_0_0,throwOnChange,false);
    this._NgFor_82_6.ngDoCheck(this,this._anchor_82,throwOnChange);
    const currVal_84_0_0:any = this.context.futureDates;
    this._NgFor_84_6.check_ngForOf(currVal_84_0_0,throwOnChange,false);
    this._NgFor_84_6.ngDoCheck(this,this._anchor_84,throwOnChange);
    const currVal_86_0_0:any = (this.context.futureDates.length > 1);
    this._NgIf_86_6.check_ngIf(currVal_86_0_0,throwOnChange,false);
    this._NgIf_86_6.ngDoCheck(this,this._anchor_86,throwOnChange);
    const currVal_90_0_0:any = this.context.stocks.length;
    this._NgIf_90_6.check_ngIf(currVal_90_0_0,throwOnChange,false);
    this._NgIf_90_6.ngDoCheck(this,this._anchor_90,throwOnChange);
    this._vc_44.detectChangesInNestedViews(throwOnChange);
    this._vc_46.detectChangesInNestedViews(throwOnChange);
    this._vc_63.detectChangesInNestedViews(throwOnChange);
    this._vc_65.detectChangesInNestedViews(throwOnChange);
    this._vc_82.detectChangesInNestedViews(throwOnChange);
    this._vc_84.detectChangesInNestedViews(throwOnChange);
    this._vc_86.detectChangesInNestedViews(throwOnChange);
    this._vc_90.detectChangesInNestedViews(throwOnChange);
    const currVal_118:any = import3.inlineInterpolate(2,'Average returns by metric for top ',(this.context.displayed? this.context.displayed.length: this.context.limit),' stocks on ',this.context.currentDate,'');
    if (import3.checkBinding(throwOnChange,this._expr_118,currVal_118)) {
      this.renderer.setText(this._text_7,currVal_118);
      this._expr_118 = currVal_118;
    }
    const currVal_121:any = import3.inlineInterpolate(1,'',this.context.currentDate,'');
    if (import3.checkBinding(throwOnChange,this._expr_121,currVal_121)) {
      this.renderer.setText(this._text_55,currVal_121);
      this._expr_121 = currVal_121;
    }
    const currVal_122:any = import3.inlineInterpolate(1,'',this.context.limit,'');
    if (import3.checkBinding(throwOnChange,this._expr_122,currVal_122)) {
      this.renderer.setText(this._text_58,currVal_122);
      this._expr_122 = currVal_122;
    }
    const currVal_123:any = import3.inlineInterpolate(1,'',this.context.spread,'');
    if (import3.checkBinding(throwOnChange,this._expr_123,currVal_123)) {
      this.renderer.setText(this._text_61,currVal_123);
      this._expr_123 = currVal_123;
    }
  }
  destroyInternal():void {
    this._vc_44.destroyNestedViews();
    this._vc_46.destroyNestedViews();
    this._vc_63.destroyNestedViews();
    this._vc_65.destroyNestedViews();
    this._vc_82.destroyNestedViews();
    this._vc_84.destroyNestedViews();
    this._vc_86.destroyNestedViews();
    this._vc_90.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 44)) { return new View_StockTable1(this.viewUtils,this,44,this._anchor_44,this._vc_44); }
    if ((nodeIndex == 46)) { return new View_StockTable2(this.viewUtils,this,46,this._anchor_46,this._vc_46); }
    if ((nodeIndex == 63)) { return new View_StockTable3(this.viewUtils,this,63,this._anchor_63,this._vc_63); }
    if ((nodeIndex == 65)) { return new View_StockTable4(this.viewUtils,this,65,this._anchor_65,this._vc_65); }
    if ((nodeIndex == 82)) { return new View_StockTable5(this.viewUtils,this,82,this._anchor_82,this._vc_82); }
    if ((nodeIndex == 84)) { return new View_StockTable6(this.viewUtils,this,84,this._anchor_84,this._vc_84); }
    if ((nodeIndex == 86)) { return new View_StockTable7(this.viewUtils,this,86,this._anchor_86,this._vc_86); }
    if ((nodeIndex == 90)) { return new View_StockTable8(this.viewUtils,this,90,this._anchor_90,this._vc_90); }
    return (null as any);
  }
}
class View_StockTable1 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StockTable1,renderType_StockTable,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
    this._expr_5 = import1.UNINITIALIZED;
    this._expr_6 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray4(4,'data-toggle','tooltip','href',''),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = (this.parentView.context.selection === this.context.$implicit.sid);
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_0,'highlight',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = (this.parentView.context.selection === this.context.$implicit.sid);
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_1,'highlight',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.$implicit.full;
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_1,'title',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import3.inlineInterpolate(1,'',this.context.$implicit.short,'');
    if (import3.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_2,currVal_6);
      this._expr_6 = currVal_6;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.select($event,this.context.$implicit.sid)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_StockTable2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StockTable2,renderType_StockTable,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.context.$implicit.short,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_StockTable3 extends import2.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import22.Wrapper_NgClass;
  _text_1:any;
  /*private*/ _expr_3:any;
  _pipe_cpercent_1_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StockTable3,renderType_StockTable,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_3 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgClass_0_3 = new import22.Wrapper_NgClass(this.parentView.parentView.injectorGet(import19.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import23.KeyValueDiffers,this.parentView.parentIndex),new import24.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_cpercent_1_0 = import3.pureProxy1((<View_StockTable0>this.parentView)._pipe_cpercent_1.transform.bind((<View_StockTable0>this.parentView)._pipe_cpercent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgClass_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    const currVal_0_0_0:any = this.parentView.context.colorMetricAvg(this.context.$implicit);
    this._NgClass_0_3.check_ngClass(currVal_0_0_0,throwOnChange,false);
    this._NgClass_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    valUnwrapper.reset();
    const currVal_3:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_cpercent_1_0,(<View_StockTable0>this.parentView)._pipe_cpercent_1.transform)(this.parentView.context.metricAverages[this.context.$implicit.sid])),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_StockTable4 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StockTable4,renderType_StockTable,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.parentView.context.benchmarks[this.context.$implicit.sid],'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_StockTable5 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StockTable5,renderType_StockTable,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
    this._expr_5 = import1.UNINITIALIZED;
    this._expr_6 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray4(4,'data-toggle','tooltip','href',''),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = (this.parentView.context.selection === this.context.$implicit.sid);
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_0,'highlight',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = (this.parentView.context.selection === this.context.$implicit.sid);
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_1,'highlight',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.$implicit.full;
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_1,'title',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import3.inlineInterpolate(1,'',this.context.$implicit.short,'');
    if (import3.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_2,currVal_6);
      this._expr_6 = currVal_6;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.select($event,this.context.$implicit.sid)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_StockTable6 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StockTable6,renderType_StockTable,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'Return on ',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_StockTable7 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StockTable7,renderType_StockTable,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Average',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_StockTable8 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import11.ViewContainer;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import12.Wrapper_NgFor;
  _text_3:any;
  _pipe_threshold_0:import26.ThresholdPipe;
  _pipe_sort_1:import27.SortPipe;
  _pipe_slice_2:import28.SlicePipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StockTable8,renderType_StockTable,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import11.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import18.TemplateRef_(this,2,this._anchor_2);
    this._NgFor_2_6 = new import12.Wrapper_NgFor(this._vc_2.vcRef,this._TemplateRef_2_5,this.parentView.parentView.injectorGet(import19.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._pipe_threshold_0 = new import26.ThresholdPipe();
    this._pipe_sort_1 = new import27.SortPipe();
    this._pipe_slice_2 = new import28.SlicePipe();
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import20.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_2_0_0:any = valUnwrapper.unwrap(this._pipe_slice_2.transform(valUnwrapper.unwrap(this._pipe_sort_1.transform(valUnwrapper.unwrap(this._pipe_threshold_0.transform(this.parentView.context.stocks,this.parentView.context.thresholds)),this.parentView.context.selection,this.parentView.context.metaDefs)),0,this.parentView.context.limit));
    this._NgFor_2_6.check_ngForOf(currVal_2_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgFor_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 2)) { return new View_StockTable9(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_StockTable9 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _vc_5:import11.ViewContainer;
  _TemplateRef_5_5:any;
  _NgFor_5_6:import12.Wrapper_NgFor;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _vc_7:import11.ViewContainer;
  _TemplateRef_7_5:any;
  _NgFor_7_6:import12.Wrapper_NgFor;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _vc_9:import11.ViewContainer;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import13.Wrapper_NgIf;
  _text_10:any;
  /*private*/ _expr_20:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StockTable9,renderType_StockTable,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_20 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_5 = new import11.ViewContainer(5,0,this,this._anchor_5);
    this._TemplateRef_5_5 = new import18.TemplateRef_(this,5,this._anchor_5);
    this._NgFor_5_6 = new import12.Wrapper_NgFor(this._vc_5.vcRef,this._TemplateRef_5_5,this.parentView.parentView.parentView.injectorGet(import19.IterableDiffers,this.parentView.parentView.parentIndex),this.parentView.parentView.ref);
    this._text_6 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_7 = new import11.ViewContainer(7,0,this,this._anchor_7);
    this._TemplateRef_7_5 = new import18.TemplateRef_(this,7,this._anchor_7);
    this._NgFor_7_6 = new import12.Wrapper_NgFor(this._vc_7.vcRef,this._TemplateRef_7_5,this.parentView.parentView.parentView.injectorGet(import19.IterableDiffers,this.parentView.parentView.parentIndex),this.parentView.parentView.ref);
    this._text_8 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_9 = new import11.ViewContainer(9,0,this,this._anchor_9);
    this._TemplateRef_9_5 = new import18.TemplateRef_(this,9,this._anchor_9);
    this._NgIf_9_6 = new import13.Wrapper_NgIf(this._vc_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._anchor_9,
      this._text_10
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import20.NgFor) && (5 === requestNodeIndex))) { return this._NgFor_5_6.context; }
    if (((token === import18.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import20.NgFor) && (7 === requestNodeIndex))) { return this._NgFor_7_6.context; }
    if (((token === import18.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import21.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5_0_0:any = this.parentView.parentView.context.metaDefs;
    this._NgFor_5_6.check_ngForOf(currVal_5_0_0,throwOnChange,false);
    this._NgFor_5_6.ngDoCheck(this,this._anchor_5,throwOnChange);
    const currVal_7_0_0:any = this.parentView.parentView.context.futureDates;
    this._NgFor_7_6.check_ngForOf(currVal_7_0_0,throwOnChange,false);
    this._NgFor_7_6.ngDoCheck(this,this._anchor_7,throwOnChange);
    const currVal_9_0_0:any = (this.parentView.parentView.context.futureDates.length > 1);
    this._NgIf_9_6.check_ngIf(currVal_9_0_0,throwOnChange,false);
    this._NgIf_9_6.ngDoCheck(this,this._anchor_9,throwOnChange);
    this._vc_5.detectChangesInNestedViews(throwOnChange);
    this._vc_7.detectChangesInNestedViews(throwOnChange);
    this._vc_9.detectChangesInNestedViews(throwOnChange);
    const currVal_20:any = import3.inlineInterpolate(1,'',(this.context.index + 1),'');
    if (import3.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setText(this._text_3,currVal_20);
      this._expr_20 = currVal_20;
    }
  }
  destroyInternal():void {
    this._vc_5.destroyNestedViews();
    this._vc_7.destroyNestedViews();
    this._vc_9.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 5)) { return new View_StockTable10(this.viewUtils,this,5,this._anchor_5,this._vc_5); }
    if ((nodeIndex == 7)) { return new View_StockTable11(this.viewUtils,this,7,this._anchor_7,this._vc_7); }
    if ((nodeIndex == 9)) { return new View_StockTable12(this.viewUtils,this,9,this._anchor_9,this._vc_9); }
    return (null as any);
  }
}
class View_StockTable10 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  _pipe_format_2_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StockTable10,renderType_StockTable,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_format_2_0 = import3.pureProxy3((<View_StockTable0>this.parentView.parentView.parentView)._pipe_format_2.transform.bind((<View_StockTable0>this.parentView.parentView.parentView)._pipe_format_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    const currVal_2:any = (this.parentView.parentView.parentView.context.selection === this.context.$implicit.sid);
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'highlight',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = ((this.context.$implicit.sid !== 't') && (this.context.$implicit.sid !== 'n'));
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_0,'table-right',currVal_3);
      this._expr_3 = currVal_3;
    }
    valUnwrapper.reset();
    const currVal_4:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_format_2_0,(<View_StockTable0>this.parentView.parentView.parentView)._pipe_format_2.transform)(this.parentView.context.$implicit[this.context.$implicit.sid],this.context.$implicit.ordinal,this.context.$implicit.sid)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_4,currVal_4))) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_StockTable11 extends import2.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import22.Wrapper_NgClass;
  _text_1:any;
  /*private*/ _expr_3:any;
  _pipe_match_3_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StockTable11,renderType_StockTable,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_3 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',new import3.InlineArray2(2,'class','table-right'),(null as any));
    this._NgClass_0_3 = new import22.Wrapper_NgClass(this.parentView.parentView.parentView.parentView.injectorGet(import19.IterableDiffers,this.parentView.parentView.parentView.parentIndex),this.parentView.parentView.parentView.parentView.injectorGet(import23.KeyValueDiffers,this.parentView.parentView.parentView.parentIndex),new import24.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_match_3_0 = import3.pureProxy2((<View_StockTable0>this.parentView.parentView.parentView)._pipe_match_3.transform.bind((<View_StockTable0>this.parentView.parentView.parentView)._pipe_match_3));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgClass_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    const currVal_0_0_0:any = 'table-right';
    this._NgClass_0_3.check_klass(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.parentView.parentView.context.colorDates(this.parentView.context.$implicit,this.context.$implicit);
    this._NgClass_0_3.check_ngClass(currVal_0_0_1,throwOnChange,false);
    this._NgClass_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    valUnwrapper.reset();
    const currVal_3:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_match_3_0,(<View_StockTable0>this.parentView.parentView.parentView)._pipe_match_3.transform)(this.parentView.context.$implicit.closes,this.context.$implicit)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_StockTable12 extends import2.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import22.Wrapper_NgClass;
  _text_1:any;
  /*private*/ _expr_3:any;
  _pipe_cpercent_1_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StockTable12,renderType_StockTable,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_3 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgClass_0_3 = new import22.Wrapper_NgClass(this.parentView.parentView.parentView.parentView.injectorGet(import19.IterableDiffers,this.parentView.parentView.parentView.parentIndex),this.parentView.parentView.parentView.parentView.injectorGet(import23.KeyValueDiffers,this.parentView.parentView.parentView.parentIndex),new import24.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_cpercent_1_1 = import3.pureProxy1((<View_StockTable0>this.parentView.parentView.parentView)._pipe_cpercent_1.transform.bind((<View_StockTable0>this.parentView.parentView.parentView)._pipe_cpercent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgClass_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    const currVal_0_0_0:any = this.parentView.parentView.parentView.context.colorStockAvg(this.parentView.context.$implicit);
    this._NgClass_0_3.check_ngClass(currVal_0_0_0,throwOnChange,false);
    this._NgClass_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    valUnwrapper.reset();
    const currVal_3:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_cpercent_1_1,(<View_StockTable0>this.parentView.parentView.parentView)._pipe_cpercent_1.transform)(this.parentView.parentView.parentView.context.stockAverages[this.parentView.context.$implicit.id])),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}